import Head from 'next/head'
import Image from 'next/image'
import { Action, Base, Button, Flow, Link, Paragraph, Space, Title } from '@jenga-ui/react'
import { Section } from '../components/Section';
import { Container } from '../components/Container';
import { TopBar } from '../components/TopBar';
import aboutIllustration from '../public/images/about-illustration.svg';
import { Card } from '../components/Card';

export default function Home() {
  return (
    <>
      <Section>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
        </Head>

        <TopBar/>
      </Section>

      <Section>
        <Container padding="15x 0">
          <Title level={1}>About Cube Dev</Title>
          <Container width={['4sp', '6sp', '8sp', '2sp']}>
            <Paragraph preset="p1">
              At Cube Dev, we&apos;re on a mission to provide developers with analytical data access layer to build modern applications. Cube.js is used by thousands of companies around the world to power customer‑facing analytics and internal business intelligence tools
            </Paragraph>
          </Container>
        </Container>

        <Container padding="0 0 3x 0">
          <Title level={2}>Our team</Title>
          <Container width={['4sp', '6sp', '8sp', '2sp']} padding="3x bottom">
            <Paragraph preset="p1">
              We are a remote‑first team distributed all over the globe with an HQ in San Francisco
            </Paragraph>
          </Container>
          <Image src={aboutIllustration} alt="Globe illustration"/>
        </Container>
      </Section>

      <Section>
        <Card>
          <Space placeContent="space-between" margin="0 auto" width={['10sp',,,'2sp']}>
            <Flow>
              <Title level={3} preset="h4">Join the team</Title>
              <Paragraph preset="p1">
                We are hiring for a broad set of positions
              </Paragraph>
            </Flow>
          </Space>
        </Card>
      </Section>
    </>
  )
}
