import Head from 'next/head'
import { Section } from '../components/Section';
import { Container } from '../components/Container';
import { TopBar } from '../components/TopBar';

export default function Page() {
  return (
    <Section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>

      <TopBar/>

      <Container padding="4x">
        Content page
      </Container>
    </Section>
  )
}
